version: "3"

vars:
  IMAGE_NAME: '{{default "training-service:latest" .IMAGE_NAME}}'
  BUILD_DIR: build
  DIST_DIR: dist
  ZIP_NAME: training-lambda.zip

tasks:
  docker-build:
    desc: create training service docker image
    dir: .
    cmds:
      - docker build -t {{.IMAGE_NAME}} .
  
  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}} {{.DIST_DIR}}

  build:
    desc: Build Lambda zip (deps + source)
    deps: [clean]
    cmds:
      - mkdir -p {{.BUILD_DIR}} {{.DIST_DIR}}
      - uv pip install --target {{.BUILD_DIR}} -r requirements-lambda.txt
      - cp -r src/* {{.BUILD_DIR}}
      - cd {{.BUILD_DIR}} && zip -r ../{{.DIST_DIR}}/{{.ZIP_NAME}} .
