version: "3"

vars:
  BUILD_DIR: build
  DIST_DIR: dist
  ZIP_NAME: feature-lambda.zip

tasks:
  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}} {{.DIST_DIR}}

  build:function:
    desc: Build Lambda function zip
    cmds:
      - mkdir -p {{.BUILD_DIR}} {{.DIST_DIR}}
      - cp -r src/* {{.BUILD_DIR}}
      - cd {{.BUILD_DIR}} && zip -r ../{{.DIST_DIR}}/{{.ZIP_NAME}} .

  build:
    desc: Clean and package the Lambda
    deps:
      - clean
      - build:function
