version: "3"

vars:
  IMAGE_NAME: '{{default "model-service:latest" .IMAGE_NAME}}'
  BUILD_DIR: build
  DIST_DIR: dist
  ZIP_NAME: model-lambda.zip

tasks:
  docker-build:
    desc: create model service docker image
    dir: .
    cmds:
      - docker build -t {{.IMAGE_NAME}} .
  
  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}} {{.DIST_DIR}}

  build:layer:
    desc: Build Lambda layer with Python dependencies
    cmds:
      - mkdir -p layer/python
      - uv pip install --target layer/python -r requirements-lambda.txt
      - cd layer && zip -r ../{{.DIST_DIR}}/ml-deps-layer.zip .

  build:function:
    desc: Build Lambda function zip (source only)
    cmds:
      - mkdir -p {{.BUILD_DIR}} {{.DIST_DIR}}
      - cp -r src/* {{.BUILD_DIR}}
      - cd {{.BUILD_DIR}} && zip -r ../{{.DIST_DIR}}/{{.ZIP_NAME}} .

  build:
    desc: Build lambda and layer
    deps: 
      - clean
      - build:layer
      - build:function
